version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - '8000:8000'
    env_file:
      - .env
    volumes:
      - ./storage:/app/storage
      - ./reports:/app/reports
      - pdf_files:/tmp/pdfs
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PYTHONPATH=/app
      - REDIS_URL=redis://:${REDIS_PASSWORD:-}@redis:6379/0
    networks:
      - app-network
    depends_on:
      - verapdf
      - redis

  worker:
    build: ./backend
    command: celery -A app.tasks.celery_app worker --loglevel=info
    env_file:
      - .env
    volumes:
      - ./storage:/app/storage
      - ./reports:/app/reports
      - pdf_files:/tmp/pdfs
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PYTHONPATH=/app
      - REDIS_URL=redis://:${REDIS_PASSWORD:-}@redis:6379/0
    networks:
      - app-network
    depends_on:
      - redis

  frontend:
    build:
      context: ./frontend
      args:
        - NEXT_PUBLIC_API_URL=http://localhost:8000
    ports:
      - '3000:3000'
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: pdf_audit_redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: >
      redis-server 
      --appendonly yes 
      --requirepass ${REDIS_PASSWORD:-defaultpass}
      --maxmemory 512mb
      --maxmemory-policy allkeys-lru
    networks:
      - app-network
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 30s
      timeout: 10s
      retries: 5

  verapdf:
    image: verapdf/cli:latest
    container_name: verapdf_service
    restart: unless-stopped
    entrypoint: ['tail', '-f', '/dev/null']
    volumes:
      - pdf_files:/tmp/pdfs
    networks:
      - app-network

volumes:
  pdf_files:
  redis_data:

networks:
  app-network:
    driver: bridge
