services:
  backend:
    build: ./backend
    ports:
      - '8000:8000'
    volumes:
      - ./storage:/app/storage
      - ./reports:/app/reports
      - pdf_files:/tmp/pdfs
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PYTHONPATH=/app
    networks:
      - app-network
    depends_on:
      - verapdf

  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    environment:
     - NEXT_PUBLIC_API_URL=http://localhost:8000 
    depends_on:
      - backend
    networks:
      - app-network

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  verapdf:
    image: verapdf/cli:latest
    container_name: verapdf_service
    restart: unless-stopped
    entrypoint: ["tail", "-f", "/dev/null"]
    volumes:
      - pdf_files:/tmp/pdfs
    networks:
      - app-network

volumes:
  pgdata:
  pdf_files:

networks:
  app-network:
    driver: bridge
